# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, verbose_name='Project Name')),
                ('pdesc', models.CharField(blank=True, max_length=100, verbose_name='Project Description')),
                ('pcreated', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('pdeadline', models.DateTimeField(verbose_name='Dead Line')),
                ('pgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
