# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint_task',
            name='sprint',
        ),
        migrations.DeleteModel(
            name='sprint_task',
        ),
    ]
