# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20170325_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='[ProjectFiles/%Y/%m')),
                ('fproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.project')),
            ],
        ),
    ]
