# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20170126_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_member',
            name='group',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sname',
            field=models.CharField(max_length=100, verbose_name='Sprint Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='cur_sprint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='Yellow', max_length=50),
        ),
        migrations.DeleteModel(
            name='group_member',
        ),
    ]
