# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_project_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ProjectFiles/%Y/%m')),
                ('fproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='project_files',
            name='fproject',
        ),
        migrations.DeleteModel(
            name='project_files',
        ),
    ]
