# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_auto_20170130_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='yellow', max_length=50),
        ),
    ]
