# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tracker', '0004_auto_20170327_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nt', 'NewTask'), ('nc', 'NewComment'), ('od', 'OverDue'), ('nd', 'NearDeadline'), ('ss', 'SprintStart'), ('se', 'SprintEnd')], max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('noti_date', models.DateTimeField()),
                ('noti_create', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
