# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_auto_20170202_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cur_sprint',
        ),
        migrations.AddField(
            model_name='sprint',
            name='task_sprint',
            field=models.ManyToManyField(to='Tracker.task'),
        ),
    ]
