# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_notification_urlid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='othermember',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
