# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_auto_20170315_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='task_sprint',
            new_name='task',
        ),
    ]
