# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_notification_othermember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nt', 'NewTask'), ('nc', 'NewComment'), ('mc', 'MentionComment'), ('od', 'OverDue'), ('nd', 'NearDeadline'), ('ss', 'SprintStart'), ('se', 'SprintEnd')], max_length=50),
        ),
    ]
