# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Tracker', '0008_auto_20170327_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='membergroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nt', 'NewTask'), ('np', 'NewProject'), ('ns', 'NewSprint'), ('nc', 'NewComment'), ('mc', 'MentionComment'), ('od', 'OverDue'), ('nd', 'NearDeadline'), ('ss', 'SprintStart'), ('se', 'SprintEnd'), ('et', 'EditTask'), ('ep', 'EditProject')], max_length=50),
        ),
    ]
