# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_auto_20170318_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mgroup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tracker.group'),
        ),
    ]
