# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0009_auto_20170328_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='screated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
