# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone



class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_auto_20170318_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comp_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
