# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_auto_20170319_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pcreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
