# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_auto_20170401_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='nproject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Tracker.project'),
            preserve_default=False,
        ),
    ]
