# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0012_notification_nproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nt', 'NewTask'), ('np', 'NewProject'), ('ns', 'NewSprint'), ('nc', 'NewComment'), ('mc', 'MentionComment'), ('od', 'OverDue'), ('nd', 'NearDeadline'), ('ss', 'SprintStart'), ('se', 'SprintEnd'), ('et', 'EditTask'), ('ep', 'EditProject'), ('uf', 'UploadFile')], max_length=50),
        ),
    ]
