# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0013_project_pdeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.member'),
        ),
    ]
