# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0015_auto_20170320_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=100, verbose_name='UserName'),
        ),
    ]
