# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0016_auto_20170320_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gname',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pcreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdesc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pname',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
    ]
