# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0017_auto_20170321_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
